using Kk.Kharts.Api.Services.IService;
using Kk.Kharts.Api.Utility.Constants;
using Kk.Kharts.Shared.Constants;
using Telegram.Bot.Types;
using Telegram.Bot.Types.Enums;

namespace Kk.Kharts.Api.Services.Telegram.Commands.Handlers;

/// <summary>
/// Handler pour la commande /generatepassword – génère un mot de passe temporaire (20 min par défaut).
/// Accessible uniquement aux comptes Root liés au bot.
/// </summary>
public sealed class GeneratePasswordCommandHandler(
    ITelegramService telegram,
    ITelegramUserService userService,
    ITemporaryAccessTokenService temporaryAccessTokenService,
    ILogger<GeneratePasswordCommandHandler> logger) : ITelegramCommandHandler
{
    private const int DefaultMinutes = 20;
    private const int MinMinutes = 5;
    private const int MaxMinutes = 120;

    public string Command => TelegramConstants.Commands.GeneratePassword;
    public string Description => "Generate a temporary support password";

    public bool RequiresAuth => true;

    public async Task HandleAsync(Message message, CancellationToken ct = default)
    {
        var chatId = message.Chat.Id;
        var telegramUserId = message.From?.Id ?? 0;

        var issuer = await userService.GetUserByTelegramIdAsync(telegramUserId, ct);
        if (issuer is null)
        {
            await ReplyNotLinkedAsync(chatId, ct);
            return;
        }

        if (!string.Equals(issuer.Role, Roles.Root, StringComparison.OrdinalIgnoreCase))
        {
            await ReplyForbiddenAsync(chatId, issuer.Nom, ct);
            return;
        }

        var requestedMinutes = ParseMinutesArgument(message.Text);
        var lifetime = TimeSpan.FromMinutes(requestedMinutes);

        var (token, plaintext) = await temporaryAccessTokenService.GenerateAsync(issuer, lifetime, ct);

        var response = $"""
            {TelegramConstants.Emojis.Key} <b>Temporary Support Password</b>

            • <b>Token:</b> <code>{plaintext}</code>
            • <b>Valide pendant:</b> {requestedMinutes} min (jusqu'à {token.ExpiresAtUtc:dd/MM HH:mm} UTC)
            • <b>Usage:</b> saisir l'email client + ce token comme mot de passe (non Root uniquement)
            • <b>Notes:</b> usage unique, sera révoqué automatiquement

            {TelegramConstants.Emojis.Warning} Supprimez ce message après l'avoir copié.
            """;

        await telegram.SendToChatAsync(chatId, response, ParseMode.Html, ct: ct);

        var auditMessage = $"""
            {TelegramConstants.Emojis.Key} Token support généré
            • Par: {telegram.EscapeHtml(issuer.Email)} (ID {issuer.Id})
            • Expire: {token.ExpiresAtUtc:dd/MM HH:mm} UTC
            • TokenId: {token.Id}
            """;

        await telegram.SendToCmdsTopicAsync(auditMessage, cancellationToken: ct);

        logger.LogInformation("Temporary password generated by {Email} (TokenId {TokenId})", issuer.Email, token.Id);
    }

    private static int ParseMinutesArgument(string? messageText)
    {
        var parts = messageText?.Split(' ', StringSplitOptions.RemoveEmptyEntries) ?? Array.Empty<string>();
        if (parts.Length < 2)
        {
            return DefaultMinutes;
        }

        if (int.TryParse(parts[1], out var minutes))
        {
            return Math.Clamp(minutes, MinMinutes, MaxMinutes);
        }

        return DefaultMinutes;
    }

    private async Task ReplyNotLinkedAsync(long chatId, CancellationToken ct)
    {
        var msg = $"""
            {TelegramConstants.Emojis.Warning} <b>Compte non lié</b>

            Pour générer un mot de passe temporaire, liez d'abord votre compte Root.
            Utilisez <code>/link email motdepasse</code> depuis le bot.
            """;
        await telegram.SendToChatAsync(chatId, msg, ParseMode.Html, ct: ct);
    }

    private async Task ReplyForbiddenAsync(long chatId, string issuerName, CancellationToken ct)
    {
        var msg = $"""
            {TelegramConstants.Emojis.Lock} <b>Accès refusé</b>

            Cette commande est réservée aux administrateurs Root.
            Utilisateur actuel: <b>{telegram.EscapeHtml(issuerName)}</b>
            """;
        await telegram.SendToChatAsync(chatId, msg, ParseMode.Html, ct: ct);
    }
}
