// <auto-generated />
using System;
using Kk.Kharts.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kk.Kharts.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250823153351_v9.2")]
    partial class v92
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("kropkharts")
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kk.Kharts.Shared.Entities.AlarmRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActiveThresholdType")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("active_threshold_type");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("description")
                        .HasColumnOrder(4);

                    b.Property<string>("DevEui")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("dev_eui")
                        .HasColumnOrder(2);

                    b.Property<int>("DeviceId")
                        .HasColumnType("int")
                        .HasColumnName("device_id")
                        .HasColumnOrder(3);

                    b.Property<int?>("DeviceModel")
                        .HasColumnType("int");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("enabled")
                        .HasColumnOrder(9);

                    b.Property<float?>("HighValue")
                        .HasColumnType("real")
                        .HasColumnName("high_value")
                        .HasColumnOrder(7);

                    b.Property<float?>("Hysteresis")
                        .HasColumnType("real")
                        .HasColumnName("hysteresis")
                        .HasColumnOrder(8);

                    b.Property<bool>("IsAlarmActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_alarm_active");

                    b.Property<bool>("IsAlarmHandled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_alarm_Handled");

                    b.Property<float?>("LowValue")
                        .HasColumnType("real")
                        .HasColumnName("low_value")
                        .HasColumnOrder(6);

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("property_name")
                        .HasColumnOrder(5);

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("alarm_rules", "kropkharts");
                });

            modelBuilder.Entity("Kk.Kharts.Shared.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("name")
                        .HasColumnOrder(1);

                    b.Property<int?>("ParentCompanyId")
                        .HasColumnType("int")
                        .HasColumnName("parent_company_id")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.HasIndex("ParentCompanyId");

                    b.ToTable("companies", "kropkharts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeviceId = new Guid("7f365e75-18f0-4c13-99c6-76e3681ab322"),
                            IsActive = true,
                            Name = "3CTEC"
                        },
                        new
                        {
                            Id = 2,
                            DeviceId = new Guid("d28cca3b-25a5-4a1a-a4bb-3aa992272d5c"),
                            IsActive = true,
                            Name = "Stratberries"
                        },
                        new
                        {
                            Id = 3,
                            DeviceId = new Guid("af8fc035-fc66-446c-8682-66e7ab03bad9"),
                            IsActive = true,
                            Name = "Invenio"
                        },
                        new
                        {
                            Id = 4,
                            DeviceId = new Guid("07b077d5-7d06-4ea6-9789-e23ddad0843f"),
                            IsActive = true,
                            Name = "Pozzobon"
                        },
                        new
                        {
                            Id = 5,
                            DeviceId = new Guid("acd50c7e-285c-4b53-b05f-ac10449fc1d9"),
                            IsActive = true,
                            Name = "Baudas"
                        });
                });

            modelBuilder.Entity("Kk.Kharts.Shared.Entities.Dashboard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("StateJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("dashboards", "kropkharts");
                });

            modelBuilder.Entity("Kk.Kharts.Shared.Entities.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("ActiveInKropKontrol")
                        .HasColumnType("bit")
                        .HasColumnName("active_in_kropkontrol")
                        .HasColumnOrder(11);

                    b.Property<float>("Battery")
                        .HasColumnType("real")
                        .HasColumnName("battery")
                        .HasColumnOrder(6);

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("societe_id")
                        .HasColumnOrder(5);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("description")
                        .HasColumnOrder(4);

                    b.Property<string>("DevEui")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("dev_eui")
                        .HasColumnOrder(2);

                    b.Property<int?>("DeviceModel")
                        .HasColumnType("int")
                        .HasColumnName("model_id")
                        .HasColumnOrder(10);

                    b.Property<DateTime>("InstallationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InstallationLocation")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Installation_location")
                        .HasColumnOrder(12);

                    b.Property<DateTime>("LastSeenAt")
                        .HasMaxLength(32)
                        .HasColumnType("datetime2")
                        .HasColumnName("last_seen_at")
                        .HasColumnOrder(8);

                    b.Property<string>("LastSendAt")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("last_send_at")
                        .HasColumnOrder(7);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("name")
                        .HasColumnOrder(3);

                    b.Property<string>("Seller")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("DeviceModel");

                    b.ToTable("devices", "kropkharts");

                    b.HasData(
                        new
                        {
                            Id = 16,
                            ActiveInKropKontrol = true,
                            Battery = 69.69f,
                            CompanyId = 3,
                            Description = "Temp & Hr - 006",
                            DevEui = "24E124136E311882",
                            DeviceModel = 7,
                            InstallationDate = new DateTime(2024, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastSeenAt = new DateTime(2017, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastSendAt = "2017 - 10 - 25 00:00:00",
                            Name = "EM300_TH_006",
                            Seller = "3CTEC"
                        },
                        new
                        {
                            Id = 12,
                            ActiveInKropKontrol = true,
                            Battery = 69.69f,
                            CompanyId = 3,
                            Description = "Temp & Hr - 002",
                            DevEui = "24E124136E317494",
                            DeviceModel = 7,
                            InstallationDate = new DateTime(2024, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastSeenAt = new DateTime(2017, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastSendAt = "2017 - 10 - 25 00:00:00",
                            Name = "EM300_TH_002",
                            Seller = "3CTEC"
                        },
                        new
                        {
                            Id = 14,
                            ActiveInKropKontrol = true,
                            Battery = 69.69f,
                            CompanyId = 3,
                            Description = "Temp & Hr - 004",
                            DevEui = "24E124136E311302",
                            DeviceModel = 7,
                            InstallationDate = new DateTime(2024, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastSeenAt = new DateTime(2017, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastSendAt = "2017 - 10 - 25 00:00:00",
                            Name = "EM300_TH_004",
                            Seller = "3CTEC"
                        },
                        new
                        {
                            Id = 13,
                            ActiveInKropKontrol = true,
                            Battery = 69.69f,
                            CompanyId = 3,
                            Description = "Temp & Hr - 003",
                            DevEui = "24E124136E317560",
                            DeviceModel = 7,
                            InstallationDate = new DateTime(2024, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastSeenAt = new DateTime(2017, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastSendAt = "2017 - 10 - 25 00:00:00",
                            Name = "EM300_TH_003",
                            Seller = "3CTEC"
                        },
                        new
                        {
                            Id = 11,
                            ActiveInKropKontrol = true,
                            Battery = 69.69f,
                            CompanyId = 3,
                            Description = "Temp & Hr - 001",
                            DevEui = "24E124136E318864",
                            DeviceModel = 7,
                            InstallationDate = new DateTime(2024, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastSeenAt = new DateTime(2017, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastSendAt = "2017 - 10 - 25 00:00:00",
                            Name = "EM300_TH_001",
                            Seller = "3CTEC"
                        },
                        new
                        {
                            Id = 15,
                            ActiveInKropKontrol = true,
                            Battery = 69.69f,
                            CompanyId = 3,
                            Description = "Temp & Hr - 005",
                            DevEui = "24E124136E316874",
                            DeviceModel = 7,
                            InstallationDate = new DateTime(2024, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastSeenAt = new DateTime(2017, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastSendAt = "2017 - 10 - 25 00:00:00",
                            Name = "EM300_TH_005",
                            Seller = "3CTEC"
                        },
                        new
                        {
                            Id = 6,
                            ActiveInKropKontrol = true,
                            Battery = 69.69f,
                            CompanyId = 3,
                            Description = "WET150 - 006",
                            DevEui = "24E124454E353679",
                            DeviceModel = 47,
                            InstallationDate = new DateTime(2024, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastSeenAt = new DateTime(2017, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastSendAt = "2017 - 10 - 25 00:00:00",
                            Name = "UC502_006",
                            Seller = "3CTEC"
                        },
                        new
                        {
                            Id = 8,
                            ActiveInKropKontrol = true,
                            Battery = 69.69f,
                            CompanyId = 3,
                            Description = "WET150 - 008",
                            DevEui = "24E124454E353717",
                            DeviceModel = 47,
                            InstallationDate = new DateTime(2024, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastSeenAt = new DateTime(2017, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastSendAt = "2017 - 10 - 25 00:00:00",
                            Name = "UC502_008",
                            Seller = "3CTEC"
                        },
                        new
                        {
                            Id = 4,
                            ActiveInKropKontrol = true,
                            Battery = 69.69f,
                            CompanyId = 3,
                            Description = "WET150 - 004",
                            DevEui = "24E124454E042988",
                            DeviceModel = 47,
                            InstallationDate = new DateTime(2024, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastSeenAt = new DateTime(2017, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastSendAt = "2017 - 10 - 25 00:00:00",
                            Name = "UC502_004",
                            Seller = "3CTEC"
                        },
                        new
                        {
                            Id = 2,
                            ActiveInKropKontrol = true,
                            Battery = 69.69f,
                            CompanyId = 3,
                            Description = "WET150 - 002",
                            DevEui = "24E124454E353580",
                            DeviceModel = 47,
                            InstallationDate = new DateTime(2024, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastSeenAt = new DateTime(2017, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastSendAt = "2017 - 10 - 25 00:00:00",
                            Name = "UC502_002",
                            Seller = "3CTEC"
                        },
                        new
                        {
                            Id = 1,
                            ActiveInKropKontrol = true,
                            Battery = 69.69f,
                            CompanyId = 3,
                            Description = "WET150 - 001",
                            DevEui = "24E124454E353385",
                            DeviceModel = 47,
                            InstallationDate = new DateTime(2024, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastSeenAt = new DateTime(2017, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastSendAt = "2017 - 10 - 25 00:00:00",
                            Name = "UC502_001",
                            Seller = "3CTEC"
                        },
                        new
                        {
                            Id = 7,
                            ActiveInKropKontrol = true,
                            Battery = 69.69f,
                            CompanyId = 3,
                            Description = "WET150 - 007",
                            DevEui = "24E124454E048465",
                            DeviceModel = 47,
                            InstallationDate = new DateTime(2024, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastSeenAt = new DateTime(2017, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastSendAt = "2017 - 10 - 25 00:00:00",
                            Name = "UC502_007",
                            Seller = "3CTEC"
                        },
                        new
                        {
                            Id = 9,
                            ActiveInKropKontrol = true,
                            Battery = 69.69f,
                            CompanyId = 3,
                            Description = "WET150 - 009",
                            DevEui = "24E124454E353777",
                            DeviceModel = 47,
                            InstallationDate = new DateTime(2024, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastSeenAt = new DateTime(2017, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastSendAt = "2017 - 10 - 25 00:00:00",
                            Name = "UC502_009",
                            Seller = "3CTEC"
                        },
                        new
                        {
                            Id = 3,
                            ActiveInKropKontrol = true,
                            Battery = 69.69f,
                            CompanyId = 3,
                            Description = "WET150 - 003",
                            DevEui = "24E124454E353875",
                            DeviceModel = 47,
                            InstallationDate = new DateTime(2024, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastSeenAt = new DateTime(2017, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastSendAt = "2017 - 10 - 25 00:00:00",
                            Name = "UC502_003",
                            Seller = "3CTEC"
                        },
                        new
                        {
                            Id = 5,
                            ActiveInKropKontrol = true,
                            Battery = 69.69f,
                            CompanyId = 3,
                            Description = "WET150 - 005",
                            DevEui = "24E124454E353844",
                            DeviceModel = 47,
                            InstallationDate = new DateTime(2024, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastSeenAt = new DateTime(2017, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastSendAt = "2017 - 10 - 25 00:00:00",
                            Name = "UC502_005",
                            Seller = "3CTEC"
                        },
                        new
                        {
                            Id = 10,
                            ActiveInKropKontrol = true,
                            Battery = 69.69f,
                            CompanyId = 3,
                            Description = "Invenio Tomate",
                            DevEui = "24E124454E352976",
                            DeviceModel = 47,
                            InstallationDate = new DateTime(2024, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastSeenAt = new DateTime(2017, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastSendAt = "2017 - 10 - 25 00:00:00",
                            Name = "UC502_010",
                            Seller = "3CTEC"
                        },
                        new
                        {
                            Id = 17,
                            ActiveInKropKontrol = true,
                            Battery = 69.69f,
                            CompanyId = 2,
                            Description = "Demo Pozzobon Modbus - Solarimètre",
                            DevEui = "24E124454E045483",
                            DeviceModel = 61,
                            InstallationDate = new DateTime(2024, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastSeenAt = new DateTime(2017, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastSendAt = "2017 - 10 - 25 00:00:00",
                            Name = "UC502_045483",
                            Seller = "3CTEC"
                        },
                        new
                        {
                            Id = 18,
                            ActiveInKropKontrol = true,
                            Battery = 69.69f,
                            CompanyId = 4,
                            Description = "Demo Pozzobon - Wet150",
                            DevEui = "24E124454E353793",
                            DeviceModel = 47,
                            InstallationDate = new DateTime(2025, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastSeenAt = new DateTime(2017, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastSendAt = "2017 - 10 - 25 00:00:00",
                            Name = "UC502_353793",
                            Seller = "3CTEC"
                        });
                });

            modelBuilder.Entity("Kk.Kharts.Shared.Entities.DeviceModel", b =>
                {
                    b.Property<int>("ModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModelId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description")
                        .HasColumnOrder(3);

                    b.Property<string>("Model")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("model")
                        .HasColumnOrder(2);

                    b.HasKey("ModelId");

                    b.ToTable("device_model", "kropkharts");

                    b.HasData(
                        new
                        {
                            ModelId = 1,
                            Description = "xxxxxxx",
                            Model = "EM300-CL"
                        },
                        new
                        {
                            ModelId = 2,
                            Description = "xxxxxxx",
                            Model = "EM300-DI"
                        },
                        new
                        {
                            ModelId = 3,
                            Description = "xxxxxxx",
                            Model = "EM300-DI_Hall"
                        },
                        new
                        {
                            ModelId = 4,
                            Description = "xxxxxxx",
                            Model = "EM300-MCS"
                        },
                        new
                        {
                            ModelId = 5,
                            Description = "xxxxxxx",
                            Model = "EM300-MLD"
                        },
                        new
                        {
                            ModelId = 6,
                            Description = "xxxxxxx",
                            Model = "EM300-SLD"
                        },
                        new
                        {
                            ModelId = 7,
                            Description = "Temperature & Humidity Sensor",
                            Model = "EM300-TH"
                        },
                        new
                        {
                            ModelId = 8,
                            Description = "xxxxxxx",
                            Model = "EM310-TILT"
                        },
                        new
                        {
                            ModelId = 9,
                            Description = "xxxxxxx",
                            Model = "EM310-UDL"
                        },
                        new
                        {
                            ModelId = 10,
                            Description = "xxxxxxx",
                            Model = "EM320-TH"
                        },
                        new
                        {
                            ModelId = 11,
                            Description = "xxxxxxx",
                            Model = "EM320-TILT"
                        },
                        new
                        {
                            ModelId = 12,
                            Description = "Reserved",
                            Model = "EM300-Reserved9"
                        },
                        new
                        {
                            ModelId = 13,
                            Description = "Reserved",
                            Model = "EM300-Reserved8"
                        },
                        new
                        {
                            ModelId = 14,
                            Description = "Reserved",
                            Model = "EM300-Reserved7"
                        },
                        new
                        {
                            ModelId = 15,
                            Description = "Reserved",
                            Model = "EM300-Reserved6"
                        },
                        new
                        {
                            ModelId = 16,
                            Description = "Reserved",
                            Model = "EM300-Reserved5"
                        },
                        new
                        {
                            ModelId = 17,
                            Description = "Reserved",
                            Model = "EM300-Reserved4"
                        },
                        new
                        {
                            ModelId = 18,
                            Description = "Reserved",
                            Model = "EM300-Reserved3"
                        },
                        new
                        {
                            ModelId = 19,
                            Description = "Reserved",
                            Model = "EM300-Reserved2"
                        },
                        new
                        {
                            ModelId = 20,
                            Description = "Reserved",
                            Model = "EM300-Reserved1"
                        },
                        new
                        {
                            ModelId = 21,
                            Description = "xxxxxxx",
                            Model = "EM500-CO2"
                        },
                        new
                        {
                            ModelId = 22,
                            Description = "xxxxxxx",
                            Model = "EM500-LGT"
                        },
                        new
                        {
                            ModelId = 23,
                            Description = "xxxxxxx",
                            Model = "EM500-PP"
                        },
                        new
                        {
                            ModelId = 24,
                            Description = "xxxxxxx",
                            Model = "EM500-PT100"
                        },
                        new
                        {
                            ModelId = 25,
                            Description = "Soil Moisture, Temperature and Electrical Conductivity Sensor",
                            Model = "EM500-SMTC"
                        },
                        new
                        {
                            ModelId = 26,
                            Description = "xxxxxxx",
                            Model = "EM500-SWL"
                        },
                        new
                        {
                            ModelId = 27,
                            Description = "xxxxxxx",
                            Model = "EM500-UDL"
                        },
                        new
                        {
                            ModelId = 28,
                            Description = "Reserved",
                            Model = "EM500-Reserved13"
                        },
                        new
                        {
                            ModelId = 29,
                            Description = "Reserved",
                            Model = "EM500-Reserved12"
                        },
                        new
                        {
                            ModelId = 30,
                            Description = "Reserved",
                            Model = "EM500-Reserved11"
                        },
                        new
                        {
                            ModelId = 31,
                            Description = "Reserved",
                            Model = "EM500-Reserved10"
                        },
                        new
                        {
                            ModelId = 32,
                            Description = "Reserved",
                            Model = "EM500-Reserved9"
                        },
                        new
                        {
                            ModelId = 33,
                            Description = "Reserved",
                            Model = "EM500-Reserved8"
                        },
                        new
                        {
                            ModelId = 34,
                            Description = "Reserved",
                            Model = "EM500-Reserved7"
                        },
                        new
                        {
                            ModelId = 35,
                            Description = "Reserved",
                            Model = "EM500-Reserved6"
                        },
                        new
                        {
                            ModelId = 36,
                            Description = "Reserved",
                            Model = "EM500-Reserved5"
                        },
                        new
                        {
                            ModelId = 37,
                            Description = "Reserved",
                            Model = "EM500-Reserved4"
                        },
                        new
                        {
                            ModelId = 38,
                            Description = "Reserved",
                            Model = "EM500-Reserved3"
                        },
                        new
                        {
                            ModelId = 39,
                            Description = "Reserved",
                            Model = "EM500-Reserved2"
                        },
                        new
                        {
                            ModelId = 40,
                            Description = "Reserved",
                            Model = "EM500-Reserved1"
                        },
                        new
                        {
                            ModelId = 41,
                            Description = "xxxxxxx",
                            Model = "UC100"
                        },
                        new
                        {
                            ModelId = 42,
                            Description = "xxxxxxx",
                            Model = "UC11-N1"
                        },
                        new
                        {
                            ModelId = 43,
                            Description = "xxxxxxx",
                            Model = "UC11-T1"
                        },
                        new
                        {
                            ModelId = 44,
                            Description = "xxxxxxx",
                            Model = "UC11XX"
                        },
                        new
                        {
                            ModelId = 45,
                            Description = "UC300 Iot Controller",
                            Model = "UC300"
                        },
                        new
                        {
                            ModelId = 46,
                            Description = "xxxxxxx",
                            Model = "UC3XXX"
                        },
                        new
                        {
                            ModelId = 47,
                            Description = "Multi-Interface Controller",
                            Model = "UC502"
                        },
                        new
                        {
                            ModelId = 48,
                            Description = "Reserved",
                            Model = "UC51X"
                        },
                        new
                        {
                            ModelId = 49,
                            Description = "Reserved",
                            Model = "UC-Series-Reserved12"
                        },
                        new
                        {
                            ModelId = 50,
                            Description = "Reserved",
                            Model = "UC-Series-Reserved11"
                        },
                        new
                        {
                            ModelId = 51,
                            Description = "Reserved",
                            Model = "UC-Series-Reserved10"
                        },
                        new
                        {
                            ModelId = 52,
                            Description = "Reserved",
                            Model = "UC-Series-Reserved9"
                        },
                        new
                        {
                            ModelId = 53,
                            Description = "Reserved",
                            Model = "UC-Series-Reserved8"
                        },
                        new
                        {
                            ModelId = 54,
                            Description = "Reserved",
                            Model = "UC-Series-Reserved7"
                        },
                        new
                        {
                            ModelId = 55,
                            Description = "Reserved",
                            Model = "UC-Series-Reserved6"
                        },
                        new
                        {
                            ModelId = 56,
                            Description = "Reserved",
                            Model = "UC-Series-Reserved5"
                        },
                        new
                        {
                            ModelId = 57,
                            Description = "Reserved",
                            Model = "UC-Series-Reserved4"
                        },
                        new
                        {
                            ModelId = 58,
                            Description = "Reserved",
                            Model = "UC-Series-Reserved3"
                        },
                        new
                        {
                            ModelId = 59,
                            Description = "Reserved",
                            Model = "UC-Series-Reserved2"
                        },
                        new
                        {
                            ModelId = 60,
                            Description = "Reserved",
                            Model = "UC-Series-Reserved1"
                        },
                        new
                        {
                            ModelId = 61,
                            Description = "Modbus",
                            Model = "U502"
                        },
                        new
                        {
                            ModelId = 62,
                            Description = "U502 Wet150 with 2 Sensors",
                            Model = "U502_2Sensors_Wet150"
                        });
                });

            modelBuilder.Entity("Kk.Kharts.Shared.Entities.DeviceParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("AlarmThreshold")
                        .HasColumnType("float")
                        .HasColumnName("alarm_threshold");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int")
                        .HasColumnName("device_id");

                    b.Property<double>("PulseConversion")
                        .HasColumnType("float")
                        .HasColumnName("pulse_conversion");

                    b.Property<float>("ValuePerPulse")
                        .HasColumnType("real");

                    b.Property<double>("WaterConversion")
                        .HasColumnType("float")
                        .HasColumnName("water_conversion");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.ToTable("devices_parameters", "kropkharts");
                });

            modelBuilder.Entity("Kk.Kharts.Shared.Entities.Em300.Em300Th", b =>
                {
                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("timestamp")
                        .HasColumnOrder(0);

                    b.Property<string>("DevEui")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("dev_eui")
                        .HasColumnOrder(1);

                    b.Property<float>("Battery")
                        .HasColumnType("real")
                        .HasColumnName("batterie")
                        .HasColumnOrder(5);

                    b.Property<int>("DeviceId")
                        .HasColumnType("int")
                        .HasColumnName("device_id")
                        .HasColumnOrder(2);

                    b.Property<float>("Humidity")
                        .HasColumnType("real")
                        .HasColumnName("humidite")
                        .HasColumnOrder(4);

                    b.Property<float>("Temperature")
                        .HasColumnType("real")
                        .HasColumnName("temperature")
                        .HasColumnOrder(3);

                    b.HasKey("Timestamp", "DevEui");

                    b.HasIndex("DeviceId");

                    b.ToTable("em300_th", "kropkharts");
                });

            modelBuilder.Entity("Kk.Kharts.Shared.Entities.Em300Di", b =>
                {
                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("timestamp")
                        .HasColumnOrder(0);

                    b.Property<string>("DevEui")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("dev_eui")
                        .HasColumnOrder(1);

                    b.Property<float>("Battery")
                        .HasColumnType("real")
                        .HasColumnName("batterie")
                        .HasColumnOrder(6);

                    b.Property<int>("DeviceId")
                        .HasColumnType("int")
                        .HasColumnName("device_id")
                        .HasColumnOrder(2);

                    b.Property<float>("Humidity")
                        .HasColumnType("real")
                        .HasColumnName("humidite")
                        .HasColumnOrder(4);

                    b.Property<float>("Temperature")
                        .HasColumnType("real")
                        .HasColumnName("temperature")
                        .HasColumnOrder(3);

                    b.Property<float>("Water")
                        .HasColumnType("real")
                        .HasColumnName("water")
                        .HasColumnOrder(5);

                    b.HasKey("Timestamp", "DevEui");

                    b.HasIndex("DeviceId");

                    b.ToTable("em300_di", "kropkharts");
                });

            modelBuilder.Entity("Kk.Kharts.Shared.Entities.PendingEmailChange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Confirmed")
                        .HasColumnType("bit");

                    b.Property<string>("NewEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PendingEmailChanges", "kropkharts");
                });

            modelBuilder.Entity("Kk.Kharts.Shared.Entities.PendingPasswordReset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Used")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PendingPasswordResets", "kropkharts");
                });

            modelBuilder.Entity("Kk.Kharts.Shared.Entities.SoilParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("A0")
                        .HasColumnType("real");

                    b.Property<float>("A1")
                        .HasColumnType("real");

                    b.Property<float>("Epsilon0")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("soil_parameters", "kropkharts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            A0 = 1.6f,
                            A1 = 8.4f,
                            Epsilon0 = -4f,
                            Name = "Minéral"
                        },
                        new
                        {
                            Id = 2,
                            A0 = 1.3f,
                            A1 = 7.7f,
                            Epsilon0 = 5.5f,
                            Name = "Organique"
                        },
                        new
                        {
                            Id = 3,
                            A0 = 1.16f,
                            A1 = 7.09f,
                            Epsilon0 = 1.8f,
                            Name = "Mélange de tourbe"
                        },
                        new
                        {
                            Id = 4,
                            A0 = 1.16f,
                            A1 = 7.41f,
                            Epsilon0 = 0f,
                            Name = "Fibre de coco"
                        },
                        new
                        {
                            Id = 5,
                            A0 = 1.04f,
                            A1 = 7.58f,
                            Epsilon0 = -0.3f,
                            Name = "Laine minérale"
                        },
                        new
                        {
                            Id = 6,
                            A0 = 1.06f,
                            A1 = 6.53f,
                            Epsilon0 = 4.1f,
                            Name = "Perlite"
                        },
                        new
                        {
                            Id = 7,
                            A0 = 1.06f,
                            A1 = 6.53f,
                            Epsilon0 = 4.1f,
                            Name = "Custom 1"
                        },
                        new
                        {
                            Id = 8,
                            A0 = 1.06f,
                            A1 = 6.53f,
                            Epsilon0 = 4.1f,
                            Name = "Custom 2"
                        },
                        new
                        {
                            Id = 9,
                            A0 = 1.06f,
                            A1 = 6.53f,
                            Epsilon0 = 4.1f,
                            Name = "Custom 3"
                        });
                });

            modelBuilder.Entity("Kk.Kharts.Shared.Entities.Technician", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("technicians", "kropkharts");
                });

            modelBuilder.Entity("Kk.Kharts.Shared.Entities.TechnicianDevice", b =>
                {
                    b.Property<int>("TechnicianId")
                        .HasColumnType("int");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.HasKey("TechnicianId", "DeviceId");

                    b.HasIndex("DeviceId");

                    b.ToTable("technician_devices", "kropkharts");
                });

            modelBuilder.Entity("Kk.Kharts.Shared.Entities.UC502.Uc502Modbus", b =>
                {
                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("timestamp")
                        .HasColumnOrder(0);

                    b.Property<string>("DevEui")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("dev_eui")
                        .HasColumnOrder(1)
                        .HasAnnotation("Relational:JsonPropertyName", "devEUI");

                    b.Property<float?>("Battery")
                        .HasColumnType("real")
                        .HasColumnName("batterie")
                        .HasColumnOrder(18)
                        .HasAnnotation("Relational:JsonPropertyName", "battery");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int")
                        .HasColumnName("device_id")
                        .HasColumnOrder(2);

                    b.Property<float?>("ModbusChannel1")
                        .HasColumnType("real")
                        .HasColumnName("modbus_chn_1")
                        .HasColumnOrder(3)
                        .HasAnnotation("Relational:JsonPropertyName", "modbus_chn_1");

                    b.Property<float?>("ModbusChannel2")
                        .HasColumnType("real")
                        .HasColumnName("modbus_chn_2")
                        .HasColumnOrder(4)
                        .HasAnnotation("Relational:JsonPropertyName", "modbus_chn_2");

                    b.Property<float?>("ModbusChannel3")
                        .HasColumnType("real")
                        .HasColumnName("modbus_chn_3")
                        .HasColumnOrder(5)
                        .HasAnnotation("Relational:JsonPropertyName", "modbus_chn_3");

                    b.Property<float?>("ModbusChannel4")
                        .HasColumnType("real")
                        .HasColumnName("modbus_chn_4")
                        .HasColumnOrder(6)
                        .HasAnnotation("Relational:JsonPropertyName", "modbus_chn_4");

                    b.Property<float?>("ModbusChannel5")
                        .HasColumnType("real")
                        .HasColumnName("modbus_chn_5")
                        .HasColumnOrder(7)
                        .HasAnnotation("Relational:JsonPropertyName", "modbus_chn_5");

                    b.Property<float?>("ModbusChannel6")
                        .HasColumnType("real")
                        .HasColumnName("modbus_chn_6")
                        .HasColumnOrder(8)
                        .HasAnnotation("Relational:JsonPropertyName", "modbus_chn_6");

                    b.HasKey("Timestamp", "DevEui");

                    b.HasIndex("DeviceId");

                    b.ToTable("uc502_modbus", "kropkharts");
                });

            modelBuilder.Entity("Kk.Kharts.Shared.Entities.UC502.Uc502Wet150", b =>
                {
                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("timestamp")
                        .HasColumnOrder(0);

                    b.Property<string>("DevEui")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("dev_eui")
                        .HasColumnOrder(1);

                    b.Property<float>("Battery")
                        .HasColumnType("real")
                        .HasColumnName("batterie")
                        .HasColumnOrder(18);

                    b.Property<float>("CoirECp")
                        .HasColumnType("real")
                        .HasColumnName("coir_ecp")
                        .HasColumnOrder(13);

                    b.Property<float>("CoirVWC")
                        .HasColumnType("real")
                        .HasColumnName("coir_vwc")
                        .HasColumnOrder(12);

                    b.Property<int>("DeviceId")
                        .HasColumnType("int")
                        .HasColumnName("device_id")
                        .HasColumnOrder(2);

                    b.Property<float>("ECb")
                        .HasColumnType("real")
                        .HasColumnName("ec_bulk")
                        .HasColumnOrder(4);

                    b.Property<float>("MinWoolECp")
                        .HasColumnType("real")
                        .HasColumnName("minwool_ecp")
                        .HasColumnOrder(15);

                    b.Property<float>("MinWoolVWC")
                        .HasColumnType("real")
                        .HasColumnName("minwool_vwc")
                        .HasColumnOrder(14);

                    b.Property<float>("MineralECp")
                        .HasColumnType("real")
                        .HasColumnName("mineral_ecp")
                        .HasColumnOrder(7);

                    b.Property<float>("MineralVWC")
                        .HasColumnType("real")
                        .HasColumnName("mineral_vwc")
                        .HasColumnOrder(6);

                    b.Property<float>("OrganicECp")
                        .HasColumnType("real")
                        .HasColumnName("organic_ecp")
                        .HasColumnOrder(9);

                    b.Property<float>("OrganicVWC")
                        .HasColumnType("real")
                        .HasColumnName("organic_vwc")
                        .HasColumnOrder(8);

                    b.Property<float>("PeatMixECp")
                        .HasColumnType("real")
                        .HasColumnName("peatmix_ecp")
                        .HasColumnOrder(11);

                    b.Property<float>("PeatMixVWC")
                        .HasColumnType("real")
                        .HasColumnName("peatmix_vwc")
                        .HasColumnOrder(10);

                    b.Property<float>("PerliteECp")
                        .HasColumnType("real")
                        .HasColumnName("perlite_ecp")
                        .HasColumnOrder(17);

                    b.Property<float>("PerliteVWC")
                        .HasColumnType("real")
                        .HasColumnName("perlite_vwc")
                        .HasColumnOrder(16);

                    b.Property<float>("Permittivite")
                        .HasColumnType("real")
                        .HasColumnName("permittivite")
                        .HasColumnOrder(3);

                    b.Property<float>("SoilTemperature")
                        .HasColumnType("real")
                        .HasColumnName("soil_temperature")
                        .HasColumnOrder(5);

                    b.HasKey("Timestamp", "DevEui");

                    b.HasIndex("DeviceId");

                    b.ToTable("wets_150", "kropkharts");
                });

            modelBuilder.Entity("Kk.Kharts.Shared.Entities.UC502.Wet150MultiSensor.Wet150MultiSensor2", b =>
                {
                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("timestamp")
                        .HasColumnOrder(0);

                    b.Property<string>("DevEui")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("dev_eui")
                        .HasColumnOrder(1);

                    b.Property<float>("Battery")
                        .HasColumnType("real")
                        .HasColumnName("batterie")
                        .HasColumnOrder(5);

                    b.Property<int>("DeviceId")
                        .HasColumnType("int")
                        .HasColumnName("device_id")
                        .HasColumnOrder(2);

                    b.Property<string>("Sdi12_1")
                        .HasMaxLength(19)
                        .HasColumnType("nvarchar(19)")
                        .HasColumnName("sdi12_1")
                        .HasColumnOrder(3);

                    b.Property<string>("Sdi12_2")
                        .HasMaxLength(19)
                        .HasColumnType("nvarchar(19)")
                        .HasColumnName("sdi12_2")
                        .HasColumnOrder(4);

                    b.HasKey("Timestamp", "DevEui");

                    b.HasIndex("DeviceId");

                    b.ToTable("wet150_multisensor_2", "kropkharts");
                });

            modelBuilder.Entity("Kk.Kharts.Shared.Entities.UC502.Wet150MultiSensor.Wet150MultiSensor3", b =>
                {
                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("timestamp")
                        .HasColumnOrder(0);

                    b.Property<string>("DevEui")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("dev_eui")
                        .HasColumnOrder(1);

                    b.Property<float>("Battery")
                        .HasColumnType("real")
                        .HasColumnName("batterie")
                        .HasColumnOrder(6);

                    b.Property<int>("DeviceId")
                        .HasColumnType("int")
                        .HasColumnName("device_id")
                        .HasColumnOrder(2);

                    b.Property<string>("Sdi12_1")
                        .HasMaxLength(19)
                        .HasColumnType("nvarchar(19)")
                        .HasColumnName("sdi12_1")
                        .HasColumnOrder(3);

                    b.Property<string>("Sdi12_2")
                        .HasMaxLength(19)
                        .HasColumnType("nvarchar(19)")
                        .HasColumnName("sdi12_2")
                        .HasColumnOrder(4);

                    b.Property<string>("Sdi12_3")
                        .HasMaxLength(19)
                        .HasColumnType("nvarchar(19)")
                        .HasColumnName("sdi12_3")
                        .HasColumnOrder(5);

                    b.HasKey("Timestamp", "DevEui");

                    b.HasIndex("DeviceId");

                    b.ToTable("wet150_multisensor_3", "kropkharts");
                });

            modelBuilder.Entity("Kk.Kharts.Shared.Entities.UC502.Wet150MultiSensor.Wet150MultiSensor4", b =>
                {
                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("timestamp")
                        .HasColumnOrder(0);

                    b.Property<string>("DevEui")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("dev_eui")
                        .HasColumnOrder(1);

                    b.Property<float>("Battery")
                        .HasColumnType("real")
                        .HasColumnName("batterie")
                        .HasColumnOrder(7);

                    b.Property<int>("DeviceId")
                        .HasColumnType("int")
                        .HasColumnName("device_id")
                        .HasColumnOrder(2);

                    b.Property<string>("Sdi12_1")
                        .HasMaxLength(19)
                        .HasColumnType("nvarchar(19)")
                        .HasColumnName("sdi12_1")
                        .HasColumnOrder(3);

                    b.Property<string>("Sdi12_2")
                        .HasMaxLength(19)
                        .HasColumnType("nvarchar(19)")
                        .HasColumnName("sdi12_2")
                        .HasColumnOrder(4);

                    b.Property<string>("Sdi12_3")
                        .HasMaxLength(19)
                        .HasColumnType("nvarchar(19)")
                        .HasColumnName("sdi12_3")
                        .HasColumnOrder(5);

                    b.Property<string>("Sdi12_4")
                        .HasMaxLength(19)
                        .HasColumnType("nvarchar(19)")
                        .HasColumnName("sdi12_4")
                        .HasColumnOrder(6);

                    b.HasKey("Timestamp", "DevEui");

                    b.HasIndex("DeviceId");

                    b.ToTable("wet150_multisensor_4", "kropkharts");
                });

            modelBuilder.Entity("Kk.Kharts.Shared.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessLevel")
                        .HasColumnType("int")
                        .HasColumnName("access_level")
                        .HasColumnOrder(5);

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("company_id")
                        .HasColumnOrder(4);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email")
                        .HasColumnOrder(2);

                    b.Property<string>("HeaderName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("3ctec")
                        .HasColumnName("header_name")
                        .HasColumnOrder(7);

                    b.Property<string>("HeaderValue")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("demo")
                        .HasColumnName("header_value")
                        .HasColumnOrder(8);

                    b.Property<string>("LastIpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("last_ip_address")
                        .HasColumnOrder(10);

                    b.Property<string>("LastUserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("last_user_agent")
                        .HasColumnOrder(9);

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nom")
                        .HasColumnOrder(1);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password")
                        .HasColumnOrder(6);

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("refresh_token")
                        .HasColumnOrder(11);

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("refresh_token_expiry_time")
                        .HasColumnOrder(12)
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("role")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("SignupDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("signup_date)\r\n")
                        .HasColumnOrder(13)
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("users", "kropkharts");
                });

            modelBuilder.Entity("Kk.Kharts.Shared.Entities.UserAlarmRule", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("AlarmRuleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "AlarmRuleId");

                    b.HasIndex("AlarmRuleId");

                    b.ToTable("user_alarm_rules", "kropkharts");
                });

            modelBuilder.Entity("Kk.Kharts.Shared.Entities.AlarmRule", b =>
                {
                    b.HasOne("Kk.Kharts.Shared.Entities.Device", "Device")
                        .WithMany("AlarmRules")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Kk.Kharts.Shared.Entities.Company", b =>
                {
                    b.HasOne("Kk.Kharts.Shared.Entities.Company", "ParentCompany")
                        .WithMany("Subsidiaries")
                        .HasForeignKey("ParentCompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCompany");
                });

            modelBuilder.Entity("Kk.Kharts.Shared.Entities.Dashboard", b =>
                {
                    b.HasOne("Kk.Kharts.Shared.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kk.Kharts.Shared.Entities.Device", b =>
                {
                    b.HasOne("Kk.Kharts.Shared.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("Kk.Kharts.Shared.Entities.DeviceModel", "ModeloNavegacao")
                        .WithMany()
                        .HasForeignKey("DeviceModel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_devices_devices_models_DeviceModelId");

                    b.Navigation("Company");

                    b.Navigation("ModeloNavegacao");
                });

            modelBuilder.Entity("Kk.Kharts.Shared.Entities.DeviceParameter", b =>
                {
                    b.HasOne("Kk.Kharts.Shared.Entities.Device", "Device")
                        .WithOne("Em300DiParameters")
                        .HasForeignKey("Kk.Kharts.Shared.Entities.DeviceParameter", "DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Kk.Kharts.Shared.Entities.Em300.Em300Th", b =>
                {
                    b.HasOne("Kk.Kharts.Shared.Entities.Device", "Device")
                        .WithMany("Em300ths")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Kk.Kharts.Shared.Entities.Em300Di", b =>
                {
                    b.HasOne("Kk.Kharts.Shared.Entities.Device", "Device")
                        .WithMany("Em300dis")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Kk.Kharts.Shared.Entities.Technician", b =>
                {
                    b.HasOne("Kk.Kharts.Shared.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kk.Kharts.Shared.Entities.TechnicianDevice", b =>
                {
                    b.HasOne("Kk.Kharts.Shared.Entities.Device", "Device")
                        .WithMany("TechnicianDevices")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kk.Kharts.Shared.Entities.Technician", "Technician")
                        .WithMany("TechnicianDevices")
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("Kk.Kharts.Shared.Entities.UC502.Uc502Modbus", b =>
                {
                    b.HasOne("Kk.Kharts.Shared.Entities.Device", "Device")
                        .WithMany("Uc502Modbuss")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Kk.Kharts.Shared.Entities.UC502.Uc502Wet150", b =>
                {
                    b.HasOne("Kk.Kharts.Shared.Entities.Device", "Device")
                        .WithMany("Uc502Wet150s")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Kk.Kharts.Shared.Entities.UC502.Wet150MultiSensor.Wet150MultiSensor2", b =>
                {
                    b.HasOne("Kk.Kharts.Shared.Entities.Device", "Device")
                        .WithMany("Wet150MultiSensors2")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Kk.Kharts.Shared.Entities.UC502.Wet150MultiSensor.Wet150MultiSensor3", b =>
                {
                    b.HasOne("Kk.Kharts.Shared.Entities.Device", "Device")
                        .WithMany("Wet150MultiSensors3")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Kk.Kharts.Shared.Entities.UC502.Wet150MultiSensor.Wet150MultiSensor4", b =>
                {
                    b.HasOne("Kk.Kharts.Shared.Entities.Device", "Device")
                        .WithMany("Wet150MultiSensors4")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Kk.Kharts.Shared.Entities.User", b =>
                {
                    b.HasOne("Kk.Kharts.Shared.Entities.Company", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Kk.Kharts.Shared.Entities.UserAlarmRule", b =>
                {
                    b.HasOne("Kk.Kharts.Shared.Entities.AlarmRule", "AlarmRule")
                        .WithMany("UserAlarmRules")
                        .HasForeignKey("AlarmRuleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Kk.Kharts.Shared.Entities.User", "User")
                        .WithMany("UserAlarmRules")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AlarmRule");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kk.Kharts.Shared.Entities.AlarmRule", b =>
                {
                    b.Navigation("UserAlarmRules");
                });

            modelBuilder.Entity("Kk.Kharts.Shared.Entities.Company", b =>
                {
                    b.Navigation("Subsidiaries");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Kk.Kharts.Shared.Entities.Device", b =>
                {
                    b.Navigation("AlarmRules");

                    b.Navigation("Em300DiParameters");

                    b.Navigation("Em300dis");

                    b.Navigation("Em300ths");

                    b.Navigation("TechnicianDevices");

                    b.Navigation("Uc502Modbuss");

                    b.Navigation("Uc502Wet150s");

                    b.Navigation("Wet150MultiSensors2");

                    b.Navigation("Wet150MultiSensors3");

                    b.Navigation("Wet150MultiSensors4");
                });

            modelBuilder.Entity("Kk.Kharts.Shared.Entities.Technician", b =>
                {
                    b.Navigation("TechnicianDevices");
                });

            modelBuilder.Entity("Kk.Kharts.Shared.Entities.User", b =>
                {
                    b.Navigation("UserAlarmRules");
                });
#pragma warning restore 612, 618
        }
    }
}
