// <auto-generated />
using System;
using Kk.Kharts.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kk.Kharts.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250602204819_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("kropkharts")
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kk.Kharts.Shared.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("name")
                        .HasColumnOrder(1);

                    b.Property<int?>("ParentCompanyId")
                        .HasColumnType("int")
                        .HasColumnName("parent_company_id")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.HasIndex("ParentCompanyId");

                    b.ToTable("companies", "kropkharts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "3CTEC"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Stratberries"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Invenio"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Pozzobon"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Baudas"
                        });
                });

            modelBuilder.Entity("Kk.Kharts.Shared.Entities.Dashboard", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("StateJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("dashboards", "kropkharts");
                });

            modelBuilder.Entity("Kk.Kharts.Shared.Entities.Device", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("ActiveInKropKontrol")
                        .HasColumnType("bit")
                        .HasColumnName("active_in_kropkontrol")
                        .HasColumnOrder(11);

                    b.Property<float>("Battery")
                        .HasColumnType("real")
                        .HasColumnName("battery")
                        .HasColumnOrder(6);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("description")
                        .HasColumnOrder(4);

                    b.Property<string>("DevEui")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("dev_eui")
                        .HasColumnOrder(2);

                    b.Property<string>("LastSeenAt")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("last_seen_at")
                        .HasColumnOrder(8);

                    b.Property<string>("LastSeenAtTime")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("last_seen_at_time")
                        .HasColumnOrder(9);

                    b.Property<string>("LastSendAt")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("last_send_at")
                        .HasColumnOrder(7);

                    b.Property<long?>("Modelo")
                        .HasColumnType("bigint")
                        .HasColumnName("model_id")
                        .HasColumnOrder(10);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("name")
                        .HasColumnOrder(3);

                    b.Property<int?>("SocieteId")
                        .HasColumnType("int")
                        .HasColumnName("societe_id")
                        .HasColumnOrder(5);

                    b.HasKey("Id");

                    b.HasIndex("Modelo");

                    b.HasIndex("SocieteId");

                    b.ToTable("devices", "kropkharts");

                    b.HasData(
                        new
                        {
                            Id = 16L,
                            ActiveInKropKontrol = true,
                            Battery = 69.69f,
                            Description = "Temp & Hr - 006",
                            DevEui = "24E124136E311882",
                            LastSeenAt = "??",
                            LastSeenAtTime = "??",
                            LastSendAt = "??",
                            Modelo = 7L,
                            Name = "EM300_TH_006",
                            SocieteId = 3
                        },
                        new
                        {
                            Id = 12L,
                            ActiveInKropKontrol = true,
                            Battery = 69.69f,
                            Description = "Temp & Hr - 002",
                            DevEui = "24E124136E317494",
                            LastSeenAt = "??",
                            LastSeenAtTime = "??",
                            LastSendAt = "??",
                            Modelo = 7L,
                            Name = "EM300_TH_002",
                            SocieteId = 3
                        },
                        new
                        {
                            Id = 14L,
                            ActiveInKropKontrol = true,
                            Battery = 69.69f,
                            Description = "Temp & Hr - 004",
                            DevEui = "24E124136E311302",
                            LastSeenAt = "??",
                            LastSeenAtTime = "??",
                            LastSendAt = "??",
                            Modelo = 7L,
                            Name = "EM300_TH_004",
                            SocieteId = 3
                        },
                        new
                        {
                            Id = 13L,
                            ActiveInKropKontrol = true,
                            Battery = 69.69f,
                            Description = "Temp & Hr - 003",
                            DevEui = "24E124136E317560",
                            LastSeenAt = "??",
                            LastSeenAtTime = "??",
                            LastSendAt = "??",
                            Modelo = 7L,
                            Name = "EM300_TH_003",
                            SocieteId = 3
                        },
                        new
                        {
                            Id = 11L,
                            ActiveInKropKontrol = true,
                            Battery = 69.69f,
                            Description = "Temp & Hr - 001",
                            DevEui = "24E124136E318864",
                            LastSeenAt = "??",
                            LastSeenAtTime = "??",
                            LastSendAt = "??",
                            Modelo = 7L,
                            Name = "EM300_TH_001",
                            SocieteId = 3
                        },
                        new
                        {
                            Id = 15L,
                            ActiveInKropKontrol = true,
                            Battery = 69.69f,
                            Description = "Temp & Hr - 005",
                            DevEui = "24E124136E316874",
                            LastSeenAt = "??",
                            LastSeenAtTime = "??",
                            LastSendAt = "??",
                            Modelo = 7L,
                            Name = "EM300_TH_005",
                            SocieteId = 3
                        },
                        new
                        {
                            Id = 6L,
                            ActiveInKropKontrol = true,
                            Battery = 69.69f,
                            Description = "WET150 - 006",
                            DevEui = "24E124454E353679",
                            LastSeenAt = "??",
                            LastSeenAtTime = "??",
                            LastSendAt = "??",
                            Modelo = 47L,
                            Name = "UC502_006",
                            SocieteId = 3
                        },
                        new
                        {
                            Id = 8L,
                            ActiveInKropKontrol = true,
                            Battery = 69.69f,
                            Description = "WET150 - 008",
                            DevEui = "24E124454E353717",
                            LastSeenAt = "??",
                            LastSeenAtTime = "??",
                            LastSendAt = "??",
                            Modelo = 47L,
                            Name = "UC502_008",
                            SocieteId = 3
                        },
                        new
                        {
                            Id = 4L,
                            ActiveInKropKontrol = true,
                            Battery = 69.69f,
                            Description = "WET150 - 004",
                            DevEui = "24E124454E042988",
                            LastSeenAt = "??",
                            LastSeenAtTime = "??",
                            LastSendAt = "??",
                            Modelo = 47L,
                            Name = "UC502_004",
                            SocieteId = 3
                        },
                        new
                        {
                            Id = 2L,
                            ActiveInKropKontrol = true,
                            Battery = 69.69f,
                            Description = "WET150 - 002",
                            DevEui = "24E124454E353580",
                            LastSeenAt = "??",
                            LastSeenAtTime = "??",
                            LastSendAt = "??",
                            Modelo = 47L,
                            Name = "UC502_002",
                            SocieteId = 3
                        },
                        new
                        {
                            Id = 1L,
                            ActiveInKropKontrol = true,
                            Battery = 69.69f,
                            Description = "WET150 - 001",
                            DevEui = "24E124454E353385",
                            LastSeenAt = "??",
                            LastSeenAtTime = "??",
                            LastSendAt = "??",
                            Modelo = 47L,
                            Name = "UC502_001",
                            SocieteId = 3
                        },
                        new
                        {
                            Id = 7L,
                            ActiveInKropKontrol = true,
                            Battery = 69.69f,
                            Description = "WET150 - 007",
                            DevEui = "24E124454E048465",
                            LastSeenAt = "??",
                            LastSeenAtTime = "??",
                            LastSendAt = "??",
                            Modelo = 47L,
                            Name = "UC502_007",
                            SocieteId = 3
                        },
                        new
                        {
                            Id = 9L,
                            ActiveInKropKontrol = true,
                            Battery = 69.69f,
                            Description = "WET150 - 009",
                            DevEui = "24E124454E353777",
                            LastSeenAt = "??",
                            LastSeenAtTime = "??",
                            LastSendAt = "??",
                            Modelo = 47L,
                            Name = "UC502_009",
                            SocieteId = 3
                        },
                        new
                        {
                            Id = 3L,
                            ActiveInKropKontrol = true,
                            Battery = 69.69f,
                            Description = "WET150 - 003",
                            DevEui = "24E124454E353875",
                            LastSeenAt = "??",
                            LastSeenAtTime = "??",
                            LastSendAt = "??",
                            Modelo = 47L,
                            Name = "UC502_003",
                            SocieteId = 3
                        },
                        new
                        {
                            Id = 5L,
                            ActiveInKropKontrol = true,
                            Battery = 69.69f,
                            Description = "WET150 - 005",
                            DevEui = "24E124454E353844",
                            LastSeenAt = "??",
                            LastSeenAtTime = "??",
                            LastSendAt = "??",
                            Modelo = 47L,
                            Name = "UC502_005",
                            SocieteId = 3
                        },
                        new
                        {
                            Id = 10L,
                            ActiveInKropKontrol = true,
                            Battery = 69.69f,
                            Description = "Invenio Tomate",
                            DevEui = "24E124454E352976",
                            LastSeenAt = "??",
                            LastSeenAtTime = "??",
                            LastSendAt = "??",
                            Modelo = 47L,
                            Name = "UC502_010",
                            SocieteId = 3
                        },
                        new
                        {
                            Id = 17L,
                            ActiveInKropKontrol = true,
                            Battery = 69.69f,
                            Description = "Demo Pozzobon Modbus - Solarimètre",
                            DevEui = "24E124454E045483",
                            LastSeenAt = "??",
                            LastSeenAtTime = "??",
                            LastSendAt = "",
                            Modelo = 61L,
                            Name = "UC502_045483",
                            SocieteId = 2
                        },
                        new
                        {
                            Id = 18L,
                            ActiveInKropKontrol = true,
                            Battery = 69.69f,
                            Description = "Demo Pozzobon - Wet150",
                            DevEui = "24E124454E353793",
                            LastSeenAt = "??",
                            LastSeenAtTime = "??",
                            LastSendAt = "",
                            Modelo = 47L,
                            Name = "UC502_353793",
                            SocieteId = 4
                        });
                });

            modelBuilder.Entity("Kk.Kharts.Shared.Entities.DeviceModel", b =>
                {
                    b.Property<long>("ModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ModelId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description")
                        .HasColumnOrder(3);

                    b.Property<string>("Model")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("model")
                        .HasColumnOrder(2);

                    b.HasKey("ModelId");

                    b.ToTable("device_model", "kropkharts");

                    b.HasData(
                        new
                        {
                            ModelId = 1L,
                            Description = "xxxxxxx",
                            Model = "EM300-CL"
                        },
                        new
                        {
                            ModelId = 2L,
                            Description = "xxxxxxx",
                            Model = "EM300-DI"
                        },
                        new
                        {
                            ModelId = 3L,
                            Description = "xxxxxxx",
                            Model = "EM300-DI_Hall"
                        },
                        new
                        {
                            ModelId = 4L,
                            Description = "xxxxxxx",
                            Model = "EM300-MCS"
                        },
                        new
                        {
                            ModelId = 5L,
                            Description = "xxxxxxx",
                            Model = "EM300-MLD"
                        },
                        new
                        {
                            ModelId = 6L,
                            Description = "xxxxxxx",
                            Model = "EM300-SLD"
                        },
                        new
                        {
                            ModelId = 7L,
                            Description = "Temperature & Humidity Sensor",
                            Model = "EM300-TH"
                        },
                        new
                        {
                            ModelId = 8L,
                            Description = "xxxxxxx",
                            Model = "EM310-TILT"
                        },
                        new
                        {
                            ModelId = 9L,
                            Description = "xxxxxxx",
                            Model = "EM310-UDL"
                        },
                        new
                        {
                            ModelId = 10L,
                            Description = "xxxxxxx",
                            Model = "EM320-TH"
                        },
                        new
                        {
                            ModelId = 11L,
                            Description = "xxxxxxx",
                            Model = "EM320-TILT"
                        },
                        new
                        {
                            ModelId = 12L,
                            Description = "Reserved",
                            Model = "EM300-Reserved9"
                        },
                        new
                        {
                            ModelId = 13L,
                            Description = "Reserved",
                            Model = "EM300-Reserved8"
                        },
                        new
                        {
                            ModelId = 14L,
                            Description = "Reserved",
                            Model = "EM300-Reserved7"
                        },
                        new
                        {
                            ModelId = 15L,
                            Description = "Reserved",
                            Model = "EM300-Reserved6"
                        },
                        new
                        {
                            ModelId = 16L,
                            Description = "Reserved",
                            Model = "EM300-Reserved5"
                        },
                        new
                        {
                            ModelId = 17L,
                            Description = "Reserved",
                            Model = "EM300-Reserved4"
                        },
                        new
                        {
                            ModelId = 18L,
                            Description = "Reserved",
                            Model = "EM300-Reserved3"
                        },
                        new
                        {
                            ModelId = 19L,
                            Description = "Reserved",
                            Model = "EM300-Reserved2"
                        },
                        new
                        {
                            ModelId = 20L,
                            Description = "Reserved",
                            Model = "EM300-Reserved1"
                        },
                        new
                        {
                            ModelId = 21L,
                            Description = "xxxxxxx",
                            Model = "EM500-CO2"
                        },
                        new
                        {
                            ModelId = 22L,
                            Description = "xxxxxxx",
                            Model = "EM500-LGT"
                        },
                        new
                        {
                            ModelId = 23L,
                            Description = "xxxxxxx",
                            Model = "EM500-PP"
                        },
                        new
                        {
                            ModelId = 24L,
                            Description = "xxxxxxx",
                            Model = "EM500-PT100"
                        },
                        new
                        {
                            ModelId = 25L,
                            Description = "Soil Moisture, Temperature and Electrical Conductivity Sensor",
                            Model = "EM500-SMTC"
                        },
                        new
                        {
                            ModelId = 26L,
                            Description = "xxxxxxx",
                            Model = "EM500-SWL"
                        },
                        new
                        {
                            ModelId = 27L,
                            Description = "xxxxxxx",
                            Model = "EM500-UDL"
                        },
                        new
                        {
                            ModelId = 28L,
                            Description = "Reserved",
                            Model = "EM500-Reserved13"
                        },
                        new
                        {
                            ModelId = 29L,
                            Description = "Reserved",
                            Model = "EM500-Reserved12"
                        },
                        new
                        {
                            ModelId = 30L,
                            Description = "Reserved",
                            Model = "EM500-Reserved11"
                        },
                        new
                        {
                            ModelId = 31L,
                            Description = "Reserved",
                            Model = "EM500-Reserved10"
                        },
                        new
                        {
                            ModelId = 32L,
                            Description = "Reserved",
                            Model = "EM500-Reserved9"
                        },
                        new
                        {
                            ModelId = 33L,
                            Description = "Reserved",
                            Model = "EM500-Reserved8"
                        },
                        new
                        {
                            ModelId = 34L,
                            Description = "Reserved",
                            Model = "EM500-Reserved7"
                        },
                        new
                        {
                            ModelId = 35L,
                            Description = "Reserved",
                            Model = "EM500-Reserved6"
                        },
                        new
                        {
                            ModelId = 36L,
                            Description = "Reserved",
                            Model = "EM500-Reserved5"
                        },
                        new
                        {
                            ModelId = 37L,
                            Description = "Reserved",
                            Model = "EM500-Reserved4"
                        },
                        new
                        {
                            ModelId = 38L,
                            Description = "Reserved",
                            Model = "EM500-Reserved3"
                        },
                        new
                        {
                            ModelId = 39L,
                            Description = "Reserved",
                            Model = "EM500-Reserved2"
                        },
                        new
                        {
                            ModelId = 40L,
                            Description = "Reserved",
                            Model = "EM500-Reserved1"
                        },
                        new
                        {
                            ModelId = 41L,
                            Description = "xxxxxxx",
                            Model = "UC100"
                        },
                        new
                        {
                            ModelId = 42L,
                            Description = "xxxxxxx",
                            Model = "UC11-N1"
                        },
                        new
                        {
                            ModelId = 43L,
                            Description = "xxxxxxx",
                            Model = "UC11-T1"
                        },
                        new
                        {
                            ModelId = 44L,
                            Description = "xxxxxxx",
                            Model = "UC11XX"
                        },
                        new
                        {
                            ModelId = 45L,
                            Description = "UC300 Iot Controller",
                            Model = "UC300"
                        },
                        new
                        {
                            ModelId = 46L,
                            Description = "xxxxxxx",
                            Model = "UC3XXX"
                        },
                        new
                        {
                            ModelId = 47L,
                            Description = "Multi-Interface Controller",
                            Model = "UC502"
                        },
                        new
                        {
                            ModelId = 48L,
                            Description = "Reserved",
                            Model = "UC51X"
                        },
                        new
                        {
                            ModelId = 49L,
                            Description = "Reserved",
                            Model = "UC-Series-Reserved12"
                        },
                        new
                        {
                            ModelId = 50L,
                            Description = "Reserved",
                            Model = "UC-Series-Reserved11"
                        },
                        new
                        {
                            ModelId = 51L,
                            Description = "Reserved",
                            Model = "UC-Series-Reserved10"
                        },
                        new
                        {
                            ModelId = 52L,
                            Description = "Reserved",
                            Model = "UC-Series-Reserved9"
                        },
                        new
                        {
                            ModelId = 53L,
                            Description = "Reserved",
                            Model = "UC-Series-Reserved8"
                        },
                        new
                        {
                            ModelId = 54L,
                            Description = "Reserved",
                            Model = "UC-Series-Reserved7"
                        },
                        new
                        {
                            ModelId = 55L,
                            Description = "Reserved",
                            Model = "UC-Series-Reserved6"
                        },
                        new
                        {
                            ModelId = 56L,
                            Description = "Reserved",
                            Model = "UC-Series-Reserved5"
                        },
                        new
                        {
                            ModelId = 57L,
                            Description = "Reserved",
                            Model = "UC-Series-Reserved4"
                        },
                        new
                        {
                            ModelId = 58L,
                            Description = "Reserved",
                            Model = "UC-Series-Reserved3"
                        },
                        new
                        {
                            ModelId = 59L,
                            Description = "Reserved",
                            Model = "UC-Series-Reserved2"
                        },
                        new
                        {
                            ModelId = 60L,
                            Description = "Reserved",
                            Model = "UC-Series-Reserved1"
                        },
                        new
                        {
                            ModelId = 61L,
                            Description = "Modbus",
                            Model = "U502"
                        });
                });

            modelBuilder.Entity("Kk.Kharts.Shared.Entities.Em300Th", b =>
                {
                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("timestamp")
                        .HasColumnOrder(0);

                    b.Property<string>("DevEui")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("dev_eui")
                        .HasColumnOrder(1);

                    b.Property<float>("Battery")
                        .HasColumnType("real")
                        .HasColumnName("batterie")
                        .HasColumnOrder(5);

                    b.Property<long>("DeviceId")
                        .HasColumnType("bigint")
                        .HasColumnName("device_id")
                        .HasColumnOrder(2);

                    b.Property<float>("Humidity")
                        .HasColumnType("real")
                        .HasColumnName("humidite")
                        .HasColumnOrder(4);

                    b.Property<float>("Temperature")
                        .HasColumnType("real")
                        .HasColumnName("temperature")
                        .HasColumnOrder(3);

                    b.HasKey("Timestamp", "DevEui");

                    b.HasIndex("DeviceId");

                    b.ToTable("em300_th", "kropkharts");
                });

            modelBuilder.Entity("Kk.Kharts.Shared.Entities.UC502.Uc502Modbus", b =>
                {
                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("timestamp")
                        .HasColumnOrder(0);

                    b.Property<string>("DevEui")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("dev_eui")
                        .HasColumnOrder(1)
                        .HasAnnotation("Relational:JsonPropertyName", "devEUI");

                    b.Property<float?>("Battery")
                        .HasColumnType("real")
                        .HasColumnName("batterie")
                        .HasColumnOrder(18)
                        .HasAnnotation("Relational:JsonPropertyName", "battery");

                    b.Property<long>("DeviceId")
                        .HasColumnType("bigint")
                        .HasColumnName("device_id")
                        .HasColumnOrder(2);

                    b.Property<float?>("ModbusChannel1")
                        .HasColumnType("real")
                        .HasColumnName("modbus_chn_1")
                        .HasColumnOrder(3)
                        .HasAnnotation("Relational:JsonPropertyName", "modbus_chn_1");

                    b.Property<float?>("ModbusChannel2")
                        .HasColumnType("real")
                        .HasColumnName("modbus_chn_2")
                        .HasColumnOrder(4)
                        .HasAnnotation("Relational:JsonPropertyName", "modbus_chn_2");

                    b.Property<float?>("ModbusChannel3")
                        .HasColumnType("real")
                        .HasColumnName("modbus_chn_3")
                        .HasColumnOrder(5)
                        .HasAnnotation("Relational:JsonPropertyName", "modbus_chn_3");

                    b.Property<float?>("ModbusChannel4")
                        .HasColumnType("real")
                        .HasColumnName("modbus_chn_4")
                        .HasColumnOrder(6)
                        .HasAnnotation("Relational:JsonPropertyName", "modbus_chn_4");

                    b.Property<float?>("ModbusChannel5")
                        .HasColumnType("real")
                        .HasColumnName("modbus_chn_5")
                        .HasColumnOrder(7)
                        .HasAnnotation("Relational:JsonPropertyName", "modbus_chn_5");

                    b.Property<float?>("ModbusChannel6")
                        .HasColumnType("real")
                        .HasColumnName("modbus_chn_6")
                        .HasColumnOrder(8)
                        .HasAnnotation("Relational:JsonPropertyName", "modbus_chn_6");

                    b.HasKey("Timestamp", "DevEui");

                    b.HasIndex("DeviceId");

                    b.ToTable("uc502_modbus", "kropkharts");
                });

            modelBuilder.Entity("Kk.Kharts.Shared.Entities.UC502.Uc502Wet150", b =>
                {
                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("timestamp")
                        .HasColumnOrder(0);

                    b.Property<string>("DevEui")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("dev_eui")
                        .HasColumnOrder(1);

                    b.Property<float>("Battery")
                        .HasColumnType("real")
                        .HasColumnName("batterie")
                        .HasColumnOrder(18);

                    b.Property<float>("CoirECp")
                        .HasColumnType("real")
                        .HasColumnName("coir_ecp")
                        .HasColumnOrder(13);

                    b.Property<float>("CoirVWC")
                        .HasColumnType("real")
                        .HasColumnName("coir_vwc")
                        .HasColumnOrder(12);

                    b.Property<long>("DeviceId")
                        .HasColumnType("bigint")
                        .HasColumnName("device_id")
                        .HasColumnOrder(2);

                    b.Property<float>("ECb")
                        .HasColumnType("real")
                        .HasColumnName("ec_bulk")
                        .HasColumnOrder(4);

                    b.Property<float>("MinWoolECp")
                        .HasColumnType("real")
                        .HasColumnName("minwool_ecp")
                        .HasColumnOrder(15);

                    b.Property<float>("MinWoolVWC")
                        .HasColumnType("real")
                        .HasColumnName("minwool_vwc")
                        .HasColumnOrder(14);

                    b.Property<float>("MineralECp")
                        .HasColumnType("real")
                        .HasColumnName("mineral_ecp")
                        .HasColumnOrder(7);

                    b.Property<float>("MineralVWC")
                        .HasColumnType("real")
                        .HasColumnName("mineral_vwc")
                        .HasColumnOrder(6);

                    b.Property<float>("OrganicECp")
                        .HasColumnType("real")
                        .HasColumnName("organic_ecp")
                        .HasColumnOrder(9);

                    b.Property<float>("OrganicVWC")
                        .HasColumnType("real")
                        .HasColumnName("organic_vwc")
                        .HasColumnOrder(8);

                    b.Property<float>("PeatMixECp")
                        .HasColumnType("real")
                        .HasColumnName("peatmix_ecp")
                        .HasColumnOrder(11);

                    b.Property<float>("PeatMixVWC")
                        .HasColumnType("real")
                        .HasColumnName("peatmix_vwc")
                        .HasColumnOrder(10);

                    b.Property<float>("PerliteECp")
                        .HasColumnType("real")
                        .HasColumnName("perlite_ecp")
                        .HasColumnOrder(17);

                    b.Property<float>("PerliteVWC")
                        .HasColumnType("real")
                        .HasColumnName("perlite_vwc")
                        .HasColumnOrder(16);

                    b.Property<float>("Permittivite")
                        .HasColumnType("real")
                        .HasColumnName("permittivite")
                        .HasColumnOrder(3);

                    b.Property<float>("SoilTemperature")
                        .HasColumnType("real")
                        .HasColumnName("soil_temperature")
                        .HasColumnOrder(5);

                    b.HasKey("Timestamp", "DevEui");

                    b.HasIndex("DeviceId");

                    b.ToTable("wets_150", "kropkharts");
                });

            modelBuilder.Entity("Kk.Kharts.Shared.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AccessLevel")
                        .HasColumnType("int")
                        .HasColumnName("access_level")
                        .HasColumnOrder(5);

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("company_id")
                        .HasColumnOrder(4);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email")
                        .HasColumnOrder(2);

                    b.Property<string>("HeaderName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("3ctec")
                        .HasColumnName("header_name")
                        .HasColumnOrder(7);

                    b.Property<string>("HeaderValue")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("demo")
                        .HasColumnName("header_value")
                        .HasColumnOrder(8);

                    b.Property<string>("LastIpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("last_ip_address")
                        .HasColumnOrder(10);

                    b.Property<string>("LastUserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("last_user_agent")
                        .HasColumnOrder(9);

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nom")
                        .HasColumnOrder(1);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password")
                        .HasColumnOrder(6);

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("refresh_token")
                        .HasColumnOrder(11);

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("refresh_token_expiry_time")
                        .HasColumnOrder(12)
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("role")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("SignupDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("signup_date)\r\n")
                        .HasColumnOrder(13)
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("users", "kropkharts");
                });

            modelBuilder.Entity("Kk.Kharts.Shared.Entities.Company", b =>
                {
                    b.HasOne("Kk.Kharts.Shared.Entities.Company", "ParentCompany")
                        .WithMany("Subsidiaries")
                        .HasForeignKey("ParentCompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCompany");
                });

            modelBuilder.Entity("Kk.Kharts.Shared.Entities.Dashboard", b =>
                {
                    b.HasOne("Kk.Kharts.Shared.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kk.Kharts.Shared.Entities.Device", b =>
                {
                    b.HasOne("Kk.Kharts.Shared.Entities.DeviceModel", "ModeloNavegacao")
                        .WithMany()
                        .HasForeignKey("Modelo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_devices_devices_models_DeviceModelId");

                    b.HasOne("Kk.Kharts.Shared.Entities.Company", "Societe")
                        .WithMany()
                        .HasForeignKey("SocieteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ModeloNavegacao");

                    b.Navigation("Societe");
                });

            modelBuilder.Entity("Kk.Kharts.Shared.Entities.Em300Th", b =>
                {
                    b.HasOne("Kk.Kharts.Shared.Entities.Device", "Device")
                        .WithMany("Em300ths")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Kk.Kharts.Shared.Entities.UC502.Uc502Modbus", b =>
                {
                    b.HasOne("Kk.Kharts.Shared.Entities.Device", "Device")
                        .WithMany("Uc502Modbuss")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Kk.Kharts.Shared.Entities.UC502.Uc502Wet150", b =>
                {
                    b.HasOne("Kk.Kharts.Shared.Entities.Device", "Device")
                        .WithMany("Uc502Wet150s")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Kk.Kharts.Shared.Entities.User", b =>
                {
                    b.HasOne("Kk.Kharts.Shared.Entities.Company", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Kk.Kharts.Shared.Entities.Company", b =>
                {
                    b.Navigation("Subsidiaries");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Kk.Kharts.Shared.Entities.Device", b =>
                {
                    b.Navigation("Em300ths");

                    b.Navigation("Uc502Modbuss");

                    b.Navigation("Uc502Wet150s");
                });
#pragma warning restore 612, 618
        }
    }
}
